// ES Module: static data — ITEMS, RECIPES, BELT_CAPS, SORTER_SPEEDS, chain/recipe constants, TECH_REQUIREMENTS
//  DATA 

var ITEMS = {
  // Ores
  iron_ore:{name:'Iron Ore',icon:'',color:'#dc2626'},
  copper_ore:{name:'Copper Ore',icon:'',color:'#ea580c'},
  stone_ore:{name:'Stone Ore',icon:'',color:'#9ca3af'},
  coal:{name:'Coal',icon:'',color:'#6b7280'},
  silicon_ore:{name:'Silicon Ore',icon:'',color:'#6366f1'},
  titanium_ore:{name:'Titanium Ore',icon:'',color:'#e2e8f0'},
  kimberlite_ore:{name:'Kimberlite Ore',icon:'',color:'#7c3aed'},
  fractal_silicon:{name:'Fractal Silicon',icon:'',color:'#4f46e5'},
  spiniform_crystal:{name:'Spiniform Stalagmite Crystal',icon:'',color:'#06b6d4'},
  unipolar_magnet:{name:'Unipolar Magnet',icon:'',color:'#ec4899'},
  optical_grating_crystal:{name:'Optical Grating Crystal',icon:'',color:'#818cf8'},
  organic_crystal_raw:{name:'Organic Crystal (raw)',icon:'',color:'#16a34a'},
  // Liquids
  fire_ice:{name:'Fire Ice',icon:'',color:'#7dd3fc'},
  crude_oil:{name:'Crude Oil',icon:'',color:'#78350f'},
  refined_oil:{name:'Refined Oil',icon:'',color:'#ca8a04'},
  water:{name:'Water',icon:'',color:'#38bdf8'},
  sulfuric_acid:{name:'Sulfuric Acid',icon:'',color:'#65a30d'},
  // Smelted materials
  iron_ingot:{name:'Iron Ingot',icon:'',color:'#b45309'},
  copper_ingot:{name:'Copper Ingot',icon:'',color:'#d97706'},
  stone_brick:{name:'Stone Brick',icon:'',color:'#78716c'},
  glass:{name:'Glass',icon:'',color:'#e0f2fe'},
  high_purity_silicon:{name:'High-Purity Silicon',icon:'',color:'#7c3aed'},
  crystal_silicon:{name:'Crystal Silicon',icon:'',color:'#3b82f6'},
  steel:{name:'Steel',icon:'',color:'#475569'},
  titanium_ingot:{name:'Titanium Ingot',icon:'',color:'#94a3b8'},
  titanium_alloy:{name:'Titanium Alloy',icon:'',color:'#64748b'},
  titanium_crystal:{name:'Titanium Crystal',icon:'',color:'#0ea5e9'},
  titanium_glass:{name:'Titanium Glass',icon:'',color:'#7dd3fc'},
  prism:{name:'Prism',icon:'',color:'#f0abfc'},
  diamond:{name:'Diamond',icon:'',color:'#a5f3fc'},
  energetic_graphite:{name:'Energized Graphite',icon:'',color:'#374151'},
  magnet:{name:'Magnet',icon:'',color:'#dc2626'},
  // Gases/fluids
  hydrogen:{name:'Hydrogen',icon:'',color:'#38bdf8'},
  deuterium:{name:'Deuterium',icon:'',color:'#fbbf24'},
  antimatter:{name:'Antimatter',icon:'',color:'#a855f7'},
  critical_photon:{name:'Critical Photon',icon:'',color:'#fef08a'},
  strange_matter:{name:'Strange Matter',icon:'',color:'#4f46e5'},
  // Chemical/intermediate
  plastic:{name:'Plastic',icon:'',color:'#f97316'},
  graphene:{name:'Graphene',icon:'',color:'#4b5563'},
  carbon_nanotube:{name:'Carbon Nanotube',icon:'',color:'#374151'},
  organic_crystal:{name:'Organic Crystal',icon:'',color:'#10b981'},
  casimir_crystal:{name:'Casimir Crystal',icon:'',color:'#f59e0b'},
  frame_material:{name:'Frame Material',icon:'',color:'#0369a1'},
  // Components
  gear:{name:'Gear',icon:'',color:'#6b7280'},
  magnetic_coil:{name:'Magnetic Coil',icon:'',color:'#2563eb'},
  circuit_board:{name:'Circuit Board',icon:'',color:'#16a34a'},
  microcrystalline:{name:'Microcrystalline Component',icon:'',color:'#0d9488'},
  processor:{name:'Processor',icon:'',color:'#7c3aed'},
  quantum_chip:{name:'Quantum Chip',icon:'',color:'#6d28d9'},
  electric_motor:{name:'Electric Motor',icon:'',color:'#2563eb'},
  em_turbine:{name:'Electromagnetic Turbine',icon:'',color:'#7c3aed'},
  super_mag_ring:{name:'Super-Magnetic Ring',icon:'',color:'#db2777'},
  particle_container:{name:'Particle Container',icon:'',color:'#0891b2'},
  particle_broadband:{name:'Particle Broadband',icon:'',color:'#0284c7'},
  plasma_exciter:{name:'Plasma Exciter',icon:'',color:'#fbbf24'},
  photon_combiner:{name:'Photon Combiner',icon:'',color:'#0ea5e9'},
  graviton_lens:{name:'Graviton Lens',icon:'',color:'#7c3aed'},
  plane_filter:{name:'Plane Filter',icon:'',color:'#0284c7'},
  annihilation_sphere:{name:'Annihilation Constraint Sphere',icon:'',color:'#dc2626'},
  thruster:{name:'Thruster',icon:'',color:'#f97316'},
  reinforced_thruster:{name:'Reinforced Thruster',icon:'',color:'#ea580c'},
  space_warper:{name:'Space Warper',icon:'',color:'#6d28d9'},
  proliferator_mk1:{name:'Proliferator Mk.I',icon:'',color:'#92400e'},
  proliferator_mk2:{name:'Proliferator Mk.II',icon:'',color:'#c2410c'},
  proliferator_mk3:{name:'Proliferator Mk.III',icon:'',color:'#dc2626'},
  // Fuels
  hydrogen_fuel_rod:{name:'Hydrogen Fuel Rod',icon:'',color:'#0284c7'},
  deuteron_fuel_rod:{name:'Deuteron Fuel Rod',icon:'',color:'#7c3aed'},
  antimatter_fuel_rod:{name:'Antimatter Fuel Rod',icon:'',color:'#a855f7'},
  combustible_unit:{name:'Combustible Unit',icon:'',color:'#ea580c'},
  // Science matrices
  em_matrix:{name:'Electromagnetic Matrix',icon:'',color:'#2563eb'},
  energy_matrix:{name:'Energy Matrix',icon:'',color:'#dc2626'},
  structure_matrix:{name:'Structure Matrix',icon:'',color:'#ca8a04'},
  information_matrix:{name:'Information Matrix',icon:'',color:'#16a34a'},
  gravity_matrix:{name:'Gravity Matrix',icon:'',color:'#7c3aed'},
  universe_matrix:{name:'Universe Matrix',icon:'',color:'#e2e8f0'},
  // Dyson sphere
  solar_sail:{name:'Solar Sail',icon:'',color:'#f59e0b'},
  dyson_component:{name:'Dyson Sphere Component',icon:'',color:'#6d28d9'},
  // Logistics
  logistics_drone:{name:'Logistics Drone',icon:'',color:'#475569'},
  logistics_vessel:{name:'Logistics Vessel',icon:'',color:'#334155'},
  small_carrier_rocket:{name:'Small Carrier Rocket',icon:'',color:'#1d4ed8'},
  foundation:{name:'Foundation',icon:'',color:'#78716c'},
  // Special/power
  power_generic:{name:'Power (generic)',icon:'',color:'#fbbf24'},
  custom:{name:'Custom Item',icon:'',color:'#6b7280'},
  // Buildings
  b_conveyor_mk1:{name:'Conveyor Belt Mk.I',icon:'',color:'#1e40af'},
  b_conveyor_mk2:{name:'Conveyor Belt Mk.II',icon:'',color:'#1d4ed8'},
  b_conveyor_mk3:{name:'Conveyor Belt Mk.III',icon:'',color:'#2563eb'},
  b_sorter_mk1:{name:'Sorter Mk.I',icon:'',color:'#0891b2'},
  b_sorter_mk2:{name:'Sorter Mk.II',icon:'',color:'#0284c7'},
  b_sorter_mk3:{name:'Sorter Mk.III',icon:'',color:'#0369a1'},
  b_splitter:{name:'Splitter',icon:'',color:'#475569'},
  b_storage_mk1:{name:'Storage Mk.I',icon:'',color:'#78716c'},
  b_storage_mk2:{name:'Storage Mk.II',icon:'',color:'#57534e'},
  b_storage_tank:{name:'Storage Tank',icon:'',color:'#44403c'},
  b_piler:{name:'Automatic Piler',icon:'',color:'#64748b'},
  b_traffic_monitor:{name:'Traffic Monitor',icon:'',color:'#374151'},
  b_spray_coater:{name:'Spray Coater',icon:'',color:'#9333ea'},
  b_mining_machine:{name:'Mining Machine',icon:'',color:'#92400e'},
  b_water_pump:{name:'Water Pump',icon:'',color:'#0369a1'},
  b_oil_extractor:{name:'Oil Extractor',icon:'',color:'#78350f'},
  b_oil_refinery:{name:'Oil Refinery',icon:'',color:'#7c2d12'},
  b_chemical_plant:{name:'Chemical Plant',icon:'',color:'#065f46'},
  b_quantum_chemical_plant:{name:'Quantum Chemical Plant',icon:'',color:'#134e4a'},
  b_arc_smelter:{name:'Arc Smelter',icon:'',color:'#9a3412'},
  b_plane_smelter:{name:'Plane Smelter',icon:'',color:'#b45309'},
  b_negentropy_smelter:{name:'Negentropy Smelter',icon:'',color:'#92400e'},
  b_assembler_mk1:{name:'Assembling Machine Mk.I',icon:'',color:'#1e3a5f'},
  b_assembler_mk2:{name:'Assembling Machine Mk.II',icon:'',color:'#1e40af'},
  b_assembler_mk3:{name:'Assembling Machine Mk.III',icon:'',color:'#1d4ed8'},
  b_recomposing_assembler:{name:'Re-Composing Assembler',icon:'',color:'#312e81'},
  b_fractionator:{name:'Fractionator',icon:'',color:'#0f766e'},
  b_particle_collider:{name:'Miniature Particle Collider',icon:'',color:'#4c1d95'},
  b_matrix_lab:{name:'Matrix Lab',icon:'',color:'#1e3a5f'},
  b_self_evolution_lab:{name:'Self-Evolution Lab',icon:'',color:'#312e81'},
  b_wind_turbine:{name:'Wind Turbine',icon:'',color:'#0891b2'},
  b_solar_panel:{name:'Solar Panel',icon:'',color:'#ca8a04'},
  b_thermal_plant:{name:'Thermal Power Plant',icon:'',color:'#4c1d95'},
  b_mini_fusion:{name:'Mini Fusion Power Plant',icon:'',color:'#3730a3'},
  b_geothermal:{name:'Geothermal Power Station',icon:'',color:'#7c2d12'},
  b_artificial_star:{name:'Artificial Star',icon:'',color:'#713f12'},
  b_ray_receiver:{name:'Ray Receiver',icon:'',color:'#1e3a5f'},
  b_energy_exchanger:{name:'Energy Exchanger',icon:'',color:'#374151'},
  b_accumulator:{name:'Accumulator',icon:'',color:'#1e40af'},
  b_tesla_tower:{name:'Tesla Tower',icon:'',color:'#1d4ed8'},
  b_wireless_tower:{name:'Wireless Power Tower',icon:'',color:'#2563eb'},
  b_satellite_substation:{name:'Satellite Substation',icon:'',color:'#1e3a5f'},
  b_planetary_logistics:{name:'Planetary Logistics Station',icon:'',color:'#0f766e'},
  b_interstellar_logistics:{name:'Interstellar Logistics Station',icon:'',color:'#065f46'},
  b_orbital_collector:{name:'Orbital Collector',icon:'',color:'#0369a1'},
  b_em_rail_ejector:{name:'EM-Rail Ejector',icon:'',color:'#7c3aed'},
  b_vertical_silo:{name:'Vertical Launching Silo',icon:'',color:'#1e3a5f'},
  b_gauss_turret:{name:'Gauss Turret',icon:'',color:'#374151'},
  b_laser_turret:{name:'Laser Turret',icon:'',color:'#dc2626'},
  b_plasma_turret:{name:'Plasma Turret',icon:'',color:'#2563eb'},
  b_missile_turret:{name:'Missile Turret',icon:'',color:'#92400e'},
  b_battlefield_analysis:{name:'Battlefield Analysis Base',icon:'',color:'#374151'},
  b_signal_tower:{name:'Signal Tower',icon:'',color:'#0891b2'},
  b_planetary_shield:{name:'Planetary Shield Generator',icon:'',color:'#1e40af'}
}

var RECIPES = {
  // === ARC SMELTER / PLANE SMELTER / NEGENTROPY SMELTER ===
  iron_ingot:       {label:'Iron Ingot',inputs:[{item:'iron_ore',qty:1}],outputs:[{item:'iron_ingot',qty:1}],time:1,machine:'arc_smelter'},
  copper_ingot:     {label:'Copper Ingot',inputs:[{item:'copper_ore',qty:1}],outputs:[{item:'copper_ingot',qty:1}],time:1,machine:'arc_smelter'},
  stone_brick:      {label:'Stone Brick',inputs:[{item:'stone_ore',qty:1}],outputs:[{item:'stone_brick',qty:1}],time:1,machine:'arc_smelter'},
  energetic_graphite:{label:'Energized Graphite',inputs:[{item:'coal',qty:2}],outputs:[{item:'energetic_graphite',qty:1}],time:2,machine:'arc_smelter'},
  glass:            {label:'Glass',inputs:[{item:'stone_ore',qty:2}],outputs:[{item:'glass',qty:1}],time:2,machine:'arc_smelter'},
  magnet:           {label:'Magnet',inputs:[{item:'iron_ore',qty:1}],outputs:[{item:'magnet',qty:1}],time:1.5,machine:'arc_smelter'},
  steel:            {label:'Steel',inputs:[{item:'iron_ingot',qty:3}],outputs:[{item:'steel',qty:1}],time:3,machine:'arc_smelter'},
  high_purity_silicon:{label:'High-Purity Silicon',inputs:[{item:'silicon_ore',qty:2}],outputs:[{item:'high_purity_silicon',qty:1}],time:2,machine:'arc_smelter'},
  crystal_silicon:  {label:'Crystal Silicon',inputs:[{item:'high_purity_silicon',qty:1}],outputs:[{item:'crystal_silicon',qty:1}],time:2,machine:'arc_smelter'},
  crystal_silicon_frac:{label:'Crystal Silicon (Fractal)',inputs:[{item:'fractal_silicon',qty:1}],outputs:[{item:'crystal_silicon',qty:2}],time:1.5,machine:'arc_smelter'},
  diamond:          {label:'Diamond',inputs:[{item:'energetic_graphite',qty:1}],outputs:[{item:'diamond',qty:1}],time:2,machine:'arc_smelter'},
  diamond_kimberlite:{label:'Diamond (Kimberlite)',inputs:[{item:'kimberlite_ore',qty:1}],outputs:[{item:'diamond',qty:2}],time:1.5,machine:'arc_smelter'},
  titanium_ingot:   {label:'Titanium Ingot',inputs:[{item:'titanium_ore',qty:2}],outputs:[{item:'titanium_ingot',qty:1}],time:2,machine:'arc_smelter'},
  titanium_alloy:   {label:'Titanium Alloy',inputs:[{item:'titanium_ingot',qty:4},{item:'steel',qty:4},{item:'sulfuric_acid',qty:8}],outputs:[{item:'titanium_alloy',qty:4}],time:12,machine:'arc_smelter'},
  silicon_ore_from_stone:{label:'Silicon Ore (from Stone)',inputs:[{item:'stone_ore',qty:10}],outputs:[{item:'silicon_ore',qty:1}],time:10,machine:'arc_smelter'},
  // === ASSEMBLER (all tiers) ===
  gear:             {label:'Gear',inputs:[{item:'iron_ingot',qty:1}],outputs:[{item:'gear',qty:1}],time:1,machine:'assembler'},
  magnetic_coil:    {label:'Magnetic Coil',inputs:[{item:'magnet',qty:2},{item:'copper_ingot',qty:1}],outputs:[{item:'magnetic_coil',qty:2}],time:1,machine:'assembler'},
  circuit_board:    {label:'Circuit Board',inputs:[{item:'iron_ingot',qty:2},{item:'copper_ingot',qty:1}],outputs:[{item:'circuit_board',qty:2}],time:1,machine:'assembler'},
  prism:            {label:'Prism',inputs:[{item:'glass',qty:3}],outputs:[{item:'prism',qty:2}],time:2,machine:'assembler'},
  titanium_glass:   {label:'Titanium Glass',inputs:[{item:'glass',qty:2},{item:'titanium_ingot',qty:2},{item:'water',qty:2}],outputs:[{item:'titanium_glass',qty:2}],time:5,machine:'assembler'},
  titanium_crystal: {label:'Titanium Crystal',inputs:[{item:'organic_crystal',qty:1},{item:'titanium_ingot',qty:3}],outputs:[{item:'titanium_crystal',qty:1}],time:4,machine:'assembler'},
  casimir_crystal:  {label:'Casimir Crystal',inputs:[{item:'titanium_crystal',qty:1},{item:'graphene',qty:2},{item:'hydrogen',qty:12}],outputs:[{item:'casimir_crystal',qty:1}],time:4,machine:'assembler'},
  casimir_crystal_optical:{label:'Casimir Crystal (Optical)',inputs:[{item:'optical_grating_crystal',qty:6},{item:'graphene',qty:2},{item:'hydrogen',qty:12}],outputs:[{item:'casimir_crystal',qty:1}],time:4,machine:'assembler'},
  microcrystalline: {label:'Microcrystalline Component',inputs:[{item:'high_purity_silicon',qty:2},{item:'copper_ingot',qty:1}],outputs:[{item:'microcrystalline',qty:1}],time:2,machine:'assembler'},
  particle_broadband:{label:'Particle Broadband',inputs:[{item:'carbon_nanotube',qty:2},{item:'crystal_silicon',qty:2},{item:'plastic',qty:1}],outputs:[{item:'particle_broadband',qty:1}],time:8,machine:'assembler'},
  plasma_exciter:   {label:'Plasma Exciter',inputs:[{item:'magnetic_coil',qty:4},{item:'prism',qty:2}],outputs:[{item:'plasma_exciter',qty:1}],time:2,machine:'assembler'},
  photon_combiner:  {label:'Photon Combiner',inputs:[{item:'prism',qty:2},{item:'circuit_board',qty:1}],outputs:[{item:'photon_combiner',qty:1}],time:3,machine:'assembler'},
  photon_combiner_optical:{label:'Photon Combiner (Optical)',inputs:[{item:'optical_grating_crystal',qty:1},{item:'circuit_board',qty:1}],outputs:[{item:'photon_combiner',qty:1}],time:3,machine:'assembler'},
  electric_motor:   {label:'Electric Motor',inputs:[{item:'iron_ingot',qty:2},{item:'gear',qty:1},{item:'magnetic_coil',qty:1}],outputs:[{item:'electric_motor',qty:1}],time:2,machine:'assembler'},
  em_turbine:       {label:'Electromagnetic Turbine',inputs:[{item:'electric_motor',qty:2},{item:'magnetic_coil',qty:2}],outputs:[{item:'em_turbine',qty:1}],time:2,machine:'assembler'},
  super_mag_ring:   {label:'Super-Magnetic Ring',inputs:[{item:'em_turbine',qty:2},{item:'magnet',qty:3},{item:'energetic_graphite',qty:1}],outputs:[{item:'super_mag_ring',qty:2}],time:3,machine:'assembler'},
  processor:        {label:'Processor',inputs:[{item:'circuit_board',qty:2},{item:'microcrystalline',qty:2}],outputs:[{item:'processor',qty:1}],time:3,machine:'assembler'},
  quantum_chip:     {label:'Quantum Chip',inputs:[{item:'processor',qty:2},{item:'plane_filter',qty:2}],outputs:[{item:'quantum_chip',qty:1}],time:6,machine:'assembler'},
  graviton_lens:    {label:'Graviton Lens',inputs:[{item:'diamond',qty:4},{item:'strange_matter',qty:1}],outputs:[{item:'graviton_lens',qty:1}],time:6,machine:'assembler'},
  space_warper:     {label:'Space Warper',inputs:[{item:'graviton_lens',qty:1}],outputs:[{item:'space_warper',qty:1}],time:10,machine:'assembler'},
  space_warper_adv: {label:'Space Warper (Advanced)',inputs:[{item:'gravity_matrix',qty:1}],outputs:[{item:'space_warper',qty:8}],time:10,machine:'assembler'},
  plane_filter:     {label:'Plane Filter',inputs:[{item:'casimir_crystal',qty:1},{item:'titanium_glass',qty:2}],outputs:[{item:'plane_filter',qty:1}],time:12,machine:'assembler'},
  particle_container:{label:'Particle Container',inputs:[{item:'em_turbine',qty:2},{item:'copper_ingot',qty:2},{item:'graphene',qty:2}],outputs:[{item:'particle_container',qty:1}],time:4,machine:'assembler'},
  particle_container_unipolar:{label:'Particle Container (Unipolar)',inputs:[{item:'unipolar_magnet',qty:10},{item:'copper_ingot',qty:2}],outputs:[{item:'particle_container',qty:1}],time:4,machine:'assembler'},
  annihilation_sphere:{label:'Annihilation Constraint Sphere',inputs:[{item:'particle_container',qty:1},{item:'processor',qty:1}],outputs:[{item:'annihilation_sphere',qty:1}],time:20,machine:'assembler'},
  thruster:         {label:'Thruster',inputs:[{item:'steel',qty:2},{item:'copper_ingot',qty:3}],outputs:[{item:'thruster',qty:1}],time:4,machine:'assembler'},
  reinforced_thruster:{label:'Reinforced Thruster',inputs:[{item:'titanium_alloy',qty:5},{item:'em_turbine',qty:5}],outputs:[{item:'reinforced_thruster',qty:1}],time:6,machine:'assembler'},
  logistics_drone:  {label:'Logistics Drone',inputs:[{item:'iron_ingot',qty:5},{item:'processor',qty:2},{item:'thruster',qty:2}],outputs:[{item:'logistics_drone',qty:1}],time:4,machine:'assembler'},
  logistics_vessel: {label:'Logistics Vessel',inputs:[{item:'titanium_alloy',qty:10},{item:'processor',qty:10},{item:'reinforced_thruster',qty:2}],outputs:[{item:'logistics_vessel',qty:1}],time:6,machine:'assembler'},
  hydrogen_fuel_rod:{label:'Hydrogen Fuel Rod',inputs:[{item:'titanium_ingot',qty:1},{item:'hydrogen',qty:10}],outputs:[{item:'hydrogen_fuel_rod',qty:2}],time:6,machine:'assembler'},
  deuteron_fuel_rod:{label:'Deuteron Fuel Rod',inputs:[{item:'titanium_alloy',qty:1},{item:'deuterium',qty:10},{item:'super_mag_ring',qty:1}],outputs:[{item:'deuteron_fuel_rod',qty:2}],time:12,machine:'assembler'},
  antimatter_fuel_rod:{label:'Antimatter Fuel Rod',inputs:[{item:'antimatter',qty:10},{item:'hydrogen',qty:10},{item:'annihilation_sphere',qty:1},{item:'titanium_alloy',qty:1}],outputs:[{item:'antimatter_fuel_rod',qty:2}],time:24,machine:'assembler'},
  combustible_unit: {label:'Combustible Unit',inputs:[{item:'coal',qty:6},{item:'plastic',qty:1}],outputs:[{item:'combustible_unit',qty:1}],time:3,machine:'assembler'},
  solar_sail:       {label:'Solar Sail',inputs:[{item:'graphene',qty:1},{item:'photon_combiner',qty:1}],outputs:[{item:'solar_sail',qty:2}],time:4,machine:'assembler'},
  dyson_component:  {label:'Dyson Sphere Component',inputs:[{item:'frame_material',qty:3},{item:'solar_sail',qty:3},{item:'processor',qty:3}],outputs:[{item:'dyson_component',qty:1}],time:8,machine:'assembler'},
  small_carrier_rocket:{label:'Small Carrier Rocket',inputs:[{item:'dyson_component',qty:2},{item:'quantum_chip',qty:2},{item:'deuteron_fuel_rod',qty:2}],outputs:[{item:'small_carrier_rocket',qty:1}],time:6,machine:'assembler'},
  frame_material:   {label:'Frame Material',inputs:[{item:'carbon_nanotube',qty:4},{item:'titanium_alloy',qty:1},{item:'high_purity_silicon',qty:1}],outputs:[{item:'frame_material',qty:1}],time:6,machine:'assembler'},
  foundation:       {label:'Foundation',inputs:[{item:'stone_brick',qty:3},{item:'steel',qty:1}],outputs:[{item:'foundation',qty:1}],time:1,machine:'assembler'},
  proliferator_mk1: {label:'Proliferator Mk.I',inputs:[{item:'coal',qty:1}],outputs:[{item:'proliferator_mk1',qty:1}],time:0.5,machine:'assembler'},
  proliferator_mk2: {label:'Proliferator Mk.II',inputs:[{item:'proliferator_mk1',qty:2},{item:'diamond',qty:1}],outputs:[{item:'proliferator_mk2',qty:1}],time:1,machine:'assembler'},
  proliferator_mk3: {label:'Proliferator Mk.III',inputs:[{item:'proliferator_mk2',qty:2},{item:'carbon_nanotube',qty:1}],outputs:[{item:'proliferator_mk3',qty:1}],time:2,machine:'assembler'},
  // === OIL REFINERY ===
  plasma_refining:  {label:'Plasma Refining',inputs:[{item:'crude_oil',qty:2}],outputs:[{item:'refined_oil',qty:2},{item:'hydrogen',qty:1}],time:4,machine:'oil_refinery'},
  xray_cracking:    {label:'X-Ray Cracking',inputs:[{item:'refined_oil',qty:1},{item:'hydrogen',qty:2}],outputs:[{item:'hydrogen',qty:3},{item:'energetic_graphite',qty:1}],time:4,machine:'oil_refinery'},
  reformed_refining:{label:'Reformed Refining',inputs:[{item:'refined_oil',qty:2},{item:'hydrogen',qty:1},{item:'coal',qty:2}],outputs:[{item:'refined_oil',qty:3}],time:4,machine:'oil_refinery'},
  // === CHEMICAL PLANT / QUANTUM CHEMICAL PLANT ===
  plastic:          {label:'Plastic',inputs:[{item:'refined_oil',qty:2},{item:'energetic_graphite',qty:1}],outputs:[{item:'plastic',qty:1}],time:3,machine:'chemical_plant'},
  graphene:         {label:'Graphene',inputs:[{item:'energetic_graphite',qty:3},{item:'sulfuric_acid',qty:1}],outputs:[{item:'graphene',qty:2}],time:3,machine:'chemical_plant'},
  graphene_fire_ice:{label:'Graphene (Fire Ice)',inputs:[{item:'fire_ice',qty:2}],outputs:[{item:'graphene',qty:2},{item:'hydrogen',qty:1}],time:2,machine:'chemical_plant'},
  carbon_nanotube:  {label:'Carbon Nanotube',inputs:[{item:'graphene',qty:3},{item:'titanium_ingot',qty:1}],outputs:[{item:'carbon_nanotube',qty:2}],time:4,machine:'chemical_plant'},
  carbon_nanotube_spiniform:{label:'Carbon Nanotube (Spiniform)',inputs:[{item:'spiniform_crystal',qty:6}],outputs:[{item:'carbon_nanotube',qty:2}],time:4,machine:'chemical_plant'},
  organic_crystal:  {label:'Organic Crystal',inputs:[{item:'plastic',qty:2},{item:'refined_oil',qty:1},{item:'water',qty:1}],outputs:[{item:'organic_crystal',qty:1}],time:6,machine:'chemical_plant'},
  organic_crystal_raw:{label:'Organic Crystal (Raw ore)',inputs:[{item:'organic_crystal_raw',qty:1}],outputs:[{item:'organic_crystal',qty:1}],time:6,machine:'chemical_plant'},
  sulfuric_acid:    {label:'Sulfuric Acid',inputs:[{item:'stone_ore',qty:6},{item:'refined_oil',qty:4},{item:'water',qty:4}],outputs:[{item:'sulfuric_acid',qty:4}],time:6,machine:'chemical_plant'},
  // === MINIATURE PARTICLE COLLIDER ===
  deuterium:        {label:'Deuterium',inputs:[{item:'hydrogen',qty:10}],outputs:[{item:'deuterium',qty:5}],time:2.5,machine:'particle_collider'},
  antimatter:       {label:'Antimatter',inputs:[{item:'critical_photon',qty:2}],outputs:[{item:'antimatter',qty:2},{item:'hydrogen',qty:2}],time:2,machine:'particle_collider'},
  strange_matter:   {label:'Strange Matter',inputs:[{item:'iron_ingot',qty:2},{item:'deuterium',qty:10},{item:'particle_container',qty:2}],outputs:[{item:'strange_matter',qty:1}],time:8,machine:'particle_collider'},
  // === MATRIX LAB ===
  em_matrix:        {label:'Electromagnetic Matrix',inputs:[{item:'magnetic_coil',qty:1},{item:'circuit_board',qty:1}],outputs:[{item:'em_matrix',qty:1}],time:3,machine:'matrix_lab'},
  energy_matrix:    {label:'Energy Matrix',inputs:[{item:'energetic_graphite',qty:2},{item:'hydrogen',qty:2}],outputs:[{item:'energy_matrix',qty:1}],time:6,machine:'matrix_lab'},
  structure_matrix: {label:'Structure Matrix',inputs:[{item:'diamond',qty:1},{item:'titanium_crystal',qty:1}],outputs:[{item:'structure_matrix',qty:1}],time:8,machine:'matrix_lab'},
  information_matrix:{label:'Information Matrix',inputs:[{item:'processor',qty:2},{item:'particle_broadband',qty:1}],outputs:[{item:'information_matrix',qty:1}],time:10,machine:'matrix_lab'},
  gravity_matrix:   {label:'Gravity Matrix',inputs:[{item:'graviton_lens',qty:1},{item:'quantum_chip',qty:1}],outputs:[{item:'gravity_matrix',qty:1}],time:24,machine:'matrix_lab'},
  universe_matrix:  {label:'Universe Matrix',inputs:[{item:'em_matrix',qty:1},{item:'energy_matrix',qty:1},{item:'structure_matrix',qty:1},{item:'information_matrix',qty:1},{item:'gravity_matrix',qty:1},{item:'antimatter',qty:1}],outputs:[{item:'universe_matrix',qty:1}],time:15,machine:'matrix_lab'},
  // === BUILDINGS (assembled in Assembler) ===
  // Logistics & Storage
  b_conveyor_mk1:   {label:'Conveyor Belt Mk.I',inputs:[{item:'iron_ingot',qty:2},{item:'gear',qty:1}],outputs:[{item:'b_conveyor_mk1',qty:3}],time:1,machine:'assembler'},
  b_conveyor_mk2:   {label:'Conveyor Belt Mk.II',inputs:[{item:'b_conveyor_mk1',qty:3},{item:'em_turbine',qty:1}],outputs:[{item:'b_conveyor_mk2',qty:3}],time:1,machine:'assembler'},
  b_conveyor_mk3:   {label:'Conveyor Belt Mk.III',inputs:[{item:'b_conveyor_mk2',qty:3},{item:'super_mag_ring',qty:1},{item:'graphene',qty:1}],outputs:[{item:'b_conveyor_mk3',qty:3}],time:1,machine:'assembler'},
  b_sorter_mk1:     {label:'Sorter Mk.I',inputs:[{item:'gear',qty:1},{item:'circuit_board',qty:1}],outputs:[{item:'b_sorter_mk1',qty:1}],time:1,machine:'assembler'},
  b_sorter_mk2:     {label:'Sorter Mk.II',inputs:[{item:'b_sorter_mk1',qty:2},{item:'electric_motor',qty:1}],outputs:[{item:'b_sorter_mk2',qty:2}],time:1,machine:'assembler'},
  b_sorter_mk3:     {label:'Sorter Mk.III',inputs:[{item:'b_sorter_mk2',qty:2},{item:'em_turbine',qty:1}],outputs:[{item:'b_sorter_mk3',qty:2}],time:1,machine:'assembler'},
  b_splitter:       {label:'Splitter',inputs:[{item:'iron_ingot',qty:3},{item:'gear',qty:2},{item:'circuit_board',qty:1}],outputs:[{item:'b_splitter',qty:1}],time:2,machine:'assembler'},
  b_storage_mk1:    {label:'Storage Mk.I',inputs:[{item:'iron_ingot',qty:4},{item:'stone_brick',qty:4}],outputs:[{item:'b_storage_mk1',qty:1}],time:2,machine:'assembler'},
  b_storage_mk2:    {label:'Storage Mk.II',inputs:[{item:'steel',qty:8},{item:'stone_brick',qty:8}],outputs:[{item:'b_storage_mk2',qty:1}],time:4,machine:'assembler'},
  b_storage_tank:   {label:'Storage Tank',inputs:[{item:'iron_ingot',qty:8},{item:'stone_brick',qty:4},{item:'glass',qty:4}],outputs:[{item:'b_storage_tank',qty:1}],time:4,machine:'assembler'},
  b_piler:          {label:'Automatic Piler',inputs:[{item:'b_conveyor_mk1',qty:1},{item:'gear',qty:1},{item:'circuit_board',qty:1}],outputs:[{item:'b_piler',qty:1}],time:1,machine:'assembler'},
  b_traffic_monitor:{label:'Traffic Monitor',inputs:[{item:'iron_ingot',qty:2},{item:'glass',qty:2},{item:'circuit_board',qty:1}],outputs:[{item:'b_traffic_monitor',qty:1}],time:2,machine:'assembler'},
  b_spray_coater:   {label:'Spray Coater',inputs:[{item:'steel',qty:4},{item:'plastic',qty:2},{item:'circuit_board',qty:2}],outputs:[{item:'b_spray_coater',qty:1}],time:3,machine:'assembler'},
  // Production buildings
  b_mining_machine: {label:'Mining Machine',inputs:[{item:'iron_ingot',qty:4},{item:'circuit_board',qty:2},{item:'magnetic_coil',qty:2},{item:'gear',qty:4}],outputs:[{item:'b_mining_machine',qty:1}],time:3,machine:'assembler'},
  b_water_pump:     {label:'Water Pump',inputs:[{item:'iron_ingot',qty:8},{item:'stone_brick',qty:4},{item:'electric_motor',qty:4},{item:'circuit_board',qty:2}],outputs:[{item:'b_water_pump',qty:1}],time:4,machine:'assembler'},
  b_oil_extractor:  {label:'Oil Extractor',inputs:[{item:'steel',qty:12},{item:'stone_brick',qty:12},{item:'circuit_board',qty:6},{item:'plasma_exciter',qty:6}],outputs:[{item:'b_oil_extractor',qty:1}],time:8,machine:'assembler'},
  b_arc_smelter:    {label:'Arc Smelter',inputs:[{item:'iron_ingot',qty:4},{item:'stone_brick',qty:2},{item:'circuit_board',qty:4},{item:'magnetic_coil',qty:4}],outputs:[{item:'b_arc_smelter',qty:1}],time:3,machine:'assembler'},
  b_plane_smelter:  {label:'Plane Smelter',inputs:[{item:'b_arc_smelter',qty:1},{item:'titanium_alloy',qty:5},{item:'circuit_board',qty:5},{item:'plasma_exciter',qty:4}],outputs:[{item:'b_plane_smelter',qty:1}],time:5,machine:'assembler'},
  b_assembler_mk1:  {label:'Assembling Machine Mk.I',inputs:[{item:'iron_ingot',qty:4},{item:'gear',qty:8},{item:'circuit_board',qty:4}],outputs:[{item:'b_assembler_mk1',qty:1}],time:2,machine:'assembler'},
  b_assembler_mk2:  {label:'Assembling Machine Mk.II',inputs:[{item:'b_assembler_mk1',qty:1},{item:'graphene',qty:4},{item:'processor',qty:1}],outputs:[{item:'b_assembler_mk2',qty:1}],time:3,machine:'assembler'},
  b_assembler_mk3:  {label:'Assembling Machine Mk.III',inputs:[{item:'b_assembler_mk2',qty:1},{item:'particle_broadband',qty:2},{item:'processor',qty:2}],outputs:[{item:'b_assembler_mk3',qty:1}],time:4,machine:'assembler'},
  b_oil_refinery:   {label:'Oil Refinery',inputs:[{item:'steel',qty:10},{item:'stone_brick',qty:10},{item:'circuit_board',qty:6},{item:'plasma_exciter',qty:6}],outputs:[{item:'b_oil_refinery',qty:1}],time:6,machine:'assembler'},
  b_chemical_plant: {label:'Chemical Plant',inputs:[{item:'steel',qty:8},{item:'stone_brick',qty:8},{item:'glass',qty:8},{item:'circuit_board',qty:2}],outputs:[{item:'b_chemical_plant',qty:1}],time:5,machine:'assembler'},
  b_fractionator:   {label:'Fractionator',inputs:[{item:'steel',qty:8},{item:'stone_brick',qty:4},{item:'gear',qty:4},{item:'graphene',qty:4}],outputs:[{item:'b_fractionator',qty:1}],time:3,machine:'assembler'},
  b_particle_collider:{label:'Miniature Particle Collider',inputs:[{item:'frame_material',qty:4},{item:'titanium_alloy',qty:8},{item:'graphene',qty:8},{item:'processor',qty:4},{item:'super_mag_ring',qty:4}],outputs:[{item:'b_particle_collider',qty:1}],time:10,machine:'assembler'},
  b_matrix_lab:     {label:'Matrix Lab',inputs:[{item:'iron_ingot',qty:8},{item:'glass',qty:4},{item:'circuit_board',qty:4},{item:'magnetic_coil',qty:4}],outputs:[{item:'b_matrix_lab',qty:1}],time:3,machine:'assembler'},
  // Power buildings
  b_wind_turbine:   {label:'Wind Turbine',inputs:[{item:'iron_ingot',qty:6},{item:'gear',qty:1},{item:'magnetic_coil',qty:3}],outputs:[{item:'b_wind_turbine',qty:1}],time:2,machine:'assembler'},
  b_solar_panel:    {label:'Solar Panel',inputs:[{item:'copper_ingot',qty:10},{item:'high_purity_silicon',qty:10},{item:'circuit_board',qty:5}],outputs:[{item:'b_solar_panel',qty:1}],time:5,machine:'assembler'},
  b_thermal_plant:  {label:'Thermal Power Plant',inputs:[{item:'iron_ingot',qty:10},{item:'stone_brick',qty:4},{item:'gear',qty:4},{item:'magnetic_coil',qty:4}],outputs:[{item:'b_thermal_plant',qty:1}],time:5,machine:'assembler'},
  b_mini_fusion:    {label:'Mini Fusion Power Plant',inputs:[{item:'titanium_alloy',qty:12},{item:'super_mag_ring',qty:6},{item:'processor',qty:12},{item:'particle_container',qty:6}],outputs:[{item:'b_mini_fusion',qty:1}],time:10,machine:'assembler'},
  b_geothermal:     {label:'Geothermal Power Station',inputs:[{item:'steel',qty:12},{item:'circuit_board',qty:8},{item:'plasma_exciter',qty:4},{item:'magnetic_coil',qty:4}],outputs:[{item:'b_geothermal',qty:1}],time:8,machine:'assembler'},
  b_accumulator:    {label:'Accumulator',inputs:[{item:'iron_ingot',qty:6},{item:'super_mag_ring',qty:6},{item:'crystal_silicon',qty:3}],outputs:[{item:'b_accumulator',qty:1}],time:5,machine:'assembler'},
  b_energy_exchanger:{label:'Energy Exchanger',inputs:[{item:'titanium_alloy',qty:20},{item:'steel',qty:40},{item:'processor',qty:20},{item:'super_mag_ring',qty:20}],outputs:[{item:'b_energy_exchanger',qty:1}],time:15,machine:'assembler'},
  b_ray_receiver:   {label:'Ray Receiver',inputs:[{item:'steel',qty:20},{item:'high_purity_silicon',qty:20},{item:'photon_combiner',qty:10},{item:'super_mag_ring',qty:20}],outputs:[{item:'b_ray_receiver',qty:1}],time:8,machine:'assembler'},
  b_artificial_star:{label:'Artificial Star',inputs:[{item:'annihilation_sphere',qty:20},{item:'titanium_alloy',qty:20},{item:'frame_material',qty:10},{item:'quantum_chip',qty:10}],outputs:[{item:'b_artificial_star',qty:1}],time:30,machine:'assembler'},
  // Power transmission
  b_tesla_tower:    {label:'Tesla Tower',inputs:[{item:'iron_ingot',qty:2},{item:'magnetic_coil',qty:1}],outputs:[{item:'b_tesla_tower',qty:1}],time:1,machine:'assembler'},
  b_wireless_tower: {label:'Wireless Power Tower',inputs:[{item:'titanium_ingot',qty:3},{item:'plasma_exciter',qty:3}],outputs:[{item:'b_wireless_tower',qty:1}],time:3,machine:'assembler'},
  b_satellite_substation:{label:'Satellite Substation',inputs:[{item:'titanium_alloy',qty:10},{item:'processor',qty:2},{item:'super_mag_ring',qty:2}],outputs:[{item:'b_satellite_substation',qty:1}],time:5,machine:'assembler'},
  // Logistics stations
  b_planetary_logistics:{label:'Planetary Logistics Station',inputs:[{item:'steel',qty:40},{item:'titanium_ingot',qty:40},{item:'processor',qty:40},{item:'particle_container',qty:20}],outputs:[{item:'b_planetary_logistics',qty:1}],time:20,machine:'assembler'},
  b_interstellar_logistics:{label:'Interstellar Logistics Station',inputs:[{item:'titanium_alloy',qty:40},{item:'titanium_glass',qty:40},{item:'processor',qty:40},{item:'particle_container',qty:20}],outputs:[{item:'b_interstellar_logistics',qty:1}],time:30,machine:'assembler'},
  b_orbital_collector:{label:'Orbital Collector',inputs:[{item:'titanium_alloy',qty:200},{item:'super_mag_ring',qty:50},{item:'reinforced_thruster',qty:50},{item:'processor',qty:200}],outputs:[{item:'b_orbital_collector',qty:1}],time:30,machine:'assembler'},
  // Dyson sphere
  b_em_rail_ejector:{label:'EM-Rail Ejector',inputs:[{item:'steel',qty:20},{item:'gear',qty:20},{item:'processor',qty:5},{item:'super_mag_ring',qty:10}],outputs:[{item:'b_em_rail_ejector',qty:1}],time:6,machine:'assembler'},
  b_vertical_silo:  {label:'Vertical Launching Silo',inputs:[{item:'titanium_alloy',qty:80},{item:'frame_material',qty:30},{item:'quantum_chip',qty:10}],outputs:[{item:'b_vertical_silo',qty:1}],time:30,machine:'assembler'},
  // Combat
  b_gauss_turret:   {label:'Gauss Turret',inputs:[{item:'titanium_alloy',qty:5},{item:'steel',qty:5},{item:'magnetic_coil',qty:5}],outputs:[{item:'b_gauss_turret',qty:1}],time:4,machine:'assembler'},
  b_laser_turret:   {label:'Laser Turret',inputs:[{item:'titanium_ingot',qty:4},{item:'photon_combiner',qty:2},{item:'circuit_board',qty:2}],outputs:[{item:'b_laser_turret',qty:1}],time:4,machine:'assembler'},
  b_plasma_turret:  {label:'Plasma Turret',inputs:[{item:'titanium_alloy',qty:5},{item:'plasma_exciter',qty:5},{item:'circuit_board',qty:5}],outputs:[{item:'b_plasma_turret',qty:1}],time:5,machine:'assembler'},
  b_missile_turret: {label:'Missile Turret',inputs:[{item:'titanium_alloy',qty:4},{item:'processor',qty:2},{item:'thruster',qty:2}],outputs:[{item:'b_missile_turret',qty:1}],time:5,machine:'assembler'},
  b_battlefield_analysis:{label:'Battlefield Analysis Base',inputs:[{item:'steel',qty:8},{item:'processor',qty:4},{item:'circuit_board',qty:4}],outputs:[{item:'b_battlefield_analysis',qty:1}],time:5,machine:'assembler'},
  b_signal_tower:   {label:'Signal Tower',inputs:[{item:'steel',qty:6},{item:'circuit_board',qty:2},{item:'plasma_exciter',qty:2}],outputs:[{item:'b_signal_tower',qty:1}],time:3,machine:'assembler'},
  b_planetary_shield:{label:'Planetary Shield Generator',inputs:[{item:'frame_material',qty:20},{item:'super_mag_ring',qty:20},{item:'particle_container',qty:20},{item:'processor',qty:20}],outputs:[{item:'b_planetary_shield',qty:1}],time:20,machine:'assembler'}
}

var BELT_CAPS = {mk1:360,mk2:720,mk3:1800};

var CHAIN_RAW_RESOURCES = {
  iron_ore:true,copper_ore:true,stone_ore:true,silicon_ore:true,
  titanium_ore:true,coal:true,fire_ice:true,hydrogen:true,
  fractal_silicon:true,kimberlite_ore:true,spiniform_crystal:true,
  optical_grating_crystal:true,organic_crystal_raw:true,
  unipolar_magnet:true,critical_photon:true
};

var PREFERRED_RECIPES = {
  crystal_silicon:   'crystal_silicon',
  diamond:           'diamond',
  graphene:          'graphene',
  carbon_nanotube:   'carbon_nanotube',
  casimir_crystal:   'casimir_crystal',
  photon_combiner:   'photon_combiner',
  particle_container:'particle_container',
  organic_crystal:   'organic_crystal',
  space_warper:      'space_warper',
  refined_oil:       'plasma_refining'
};

var BuildState = {
  product:'', targetRate:60,
  beltTier:'mk1', sorterTier:'mk1', assemblerTier:'mk2',
  searchText:''
};

var SORTER_SPEEDS = {mk1:1.5,mk2:3,mk3:6};

var TECH_REQUIREMENTS = [
  // Early game — EM Matrix (Blue) only
  {key:'em_basic',        name:'Electromagnetic Matrix',        costs:{em_matrix:10}},
  {key:'basic_auto',      name:'Basic Automation',              costs:{em_matrix:40}},
  {key:'drive_engine',    name:'Drive Engine',                  costs:{em_matrix:40}},
  {key:'steel_smelt',     name:'Steel Smelting',                costs:{em_matrix:40}},
  {key:'hi_eff_plasma',   name:'High-Eff. Plasma Control (Assembler Mk.II)', costs:{em_matrix:160}},
  {key:'plasma_refine',   name:'Plasma Refining (Oil Refinery)',costs:{em_matrix:100}},
  {key:'semi_material',   name:'Semiconductor Material',        costs:{em_matrix:100}},
  {key:'applied_super',   name:'Applied Superconductor',        costs:{em_matrix:160}},
  {key:'particle_broad',  name:'Particle Broadband Conductor',  costs:{em_matrix:160}},
  {key:'grav_refract',    name:'Gravity Wave Refraction',       costs:{em_matrix:400}},
  // Mid game — EM + Energy Matrix (Red)
  {key:'energy_matrix',   name:'Energy Matrix',                 costs:{em_matrix:100, energy_matrix:200}},
  {key:'xray_crack',      name:'X-Ray Cracking',                costs:{em_matrix:100, energy_matrix:200}},
  {key:'hi_strength_exp', name:'High-Strength Explosive',       costs:{em_matrix:200, energy_matrix:100}},
  {key:'gas_giant_ext',   name:'Gas Giant Extraction',          costs:{em_matrix:200, energy_matrix:200}},
  {key:'adv_chem',        name:'Advanced Chemistry',            costs:{em_matrix:200, energy_matrix:200}},
  {key:'ion_thruster',    name:'Ion Thrusters',                 costs:{em_matrix:400, energy_matrix:400}},
  // Mid-late — EM + Energy + Structure Matrix (Yellow)
  {key:'struct_matrix',   name:'Structure Matrix',              costs:{em_matrix:100, energy_matrix:200, structure_matrix:200}},
  {key:'particle_coll',   name:'Particle Collider Tech',        costs:{em_matrix:400, energy_matrix:400, structure_matrix:200}},
  {key:'nuclear_fusion',  name:'Controlled Nuclear Fusion',     costs:{em_matrix:400, energy_matrix:400, structure_matrix:400}},
  {key:'assembler_mk3',   name:'Assembler Mk.III',              costs:{em_matrix:400, energy_matrix:400, structure_matrix:400}},
  {key:'plane_smelter',   name:'Plane Smelter',                 costs:{em_matrix:400, energy_matrix:400, structure_matrix:400}},
  // Late game — all 4 (+ Information Matrix, Purple)
  {key:'info_matrix',     name:'Information Matrix',            costs:{em_matrix:200, energy_matrix:200, structure_matrix:200, information_matrix:400}},
  {key:'dyson_sphere',    name:'Dyson Sphere System',           costs:{em_matrix:400, energy_matrix:400, structure_matrix:400, information_matrix:400}},
  {key:'pls_tech',        name:'Planetary Logistics System',    costs:{em_matrix:400, energy_matrix:400, structure_matrix:400, information_matrix:400}},
  {key:'ils_tech',        name:'Interstellar Logistics System', costs:{em_matrix:1000, energy_matrix:1000, structure_matrix:1000, information_matrix:1000}},
  {key:'quantum_chip',    name:'Quantum Chip Production',       costs:{em_matrix:400, energy_matrix:400, structure_matrix:400, information_matrix:400}},
  // End game — all 5 (+ Gravity Matrix, Green)
  {key:'grav_matrix',     name:'Gravity Matrix',                costs:{em_matrix:400, energy_matrix:400, structure_matrix:400, information_matrix:400, gravity_matrix:400}},
  {key:'mass_energy',     name:'Mass-Energy Storage',           costs:{em_matrix:1000, energy_matrix:1000, structure_matrix:1000, information_matrix:1000, gravity_matrix:1000}},
  {key:'virtual_reality', name:'Virtual Reality',               costs:{em_matrix:2000, energy_matrix:2000, structure_matrix:2000, information_matrix:2000, gravity_matrix:2000}},
  // Universe Matrix era
  {key:'universe_matrix', name:'Universe Matrix',               costs:{em_matrix:1000, energy_matrix:1000, structure_matrix:1000, information_matrix:1000, gravity_matrix:1000, universe_matrix:500}},
  {key:'univ_explore_1',  name:'Universe Exploration Lv.1',     costs:{em_matrix:5000, energy_matrix:5000, structure_matrix:5000, information_matrix:5000, gravity_matrix:5000, universe_matrix:5000}}
];

export { ITEMS, RECIPES, BELT_CAPS, SORTER_SPEEDS, CHAIN_RAW_RESOURCES, PREFERRED_RECIPES, TECH_REQUIREMENTS, BuildState };
